name: SwiftUI-DesignSystem
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
targets:
  DesignSystemDemo:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: 
      - path: App
      - path: Assets
      - path: Core
      - path: Presentation
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        INFOPLIST_KEY_CFBundleIcons:
          CFBundleAlternateIcons:
            AppIcon-Dark:
              CFBundleIconFiles: ["AppIcon-Dark"]
              UIPrerenderedIcon: YES
            AppIcon-Vibrant:
              CFBundleIconFiles: ["AppIcon-Vibrant"]
              UIPrerenderedIcon: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.example.SwiftUI-DesignSystem
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        DEVELOPMENT_ASSET_PATHS: '"Assets"'
